### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by wangzwYYDS** [zhangtaolab/Plant_DNA_LLMs#12]
i installed the model and software  , when i tried the example run .. but error ...

[admin1 PDLLMs]$ python model_inference.py -m inference/models/plant-dnagpt-BPE-promoter/ -s 'TTACTAAATTTATAACGATTTTTTATCTAACTTTAGCTCATCAATCTTTACCGTGTCAAAATTTAGTGCCAAGAAGCAGACATGGCCCGATGATCTTTTACCCTGTTTTCATAGCTCGCGAGCCGCGACCTGTGTCCAACCTCAACGGTCACTGCAGTCCCAGCACCTCAGCAGCCTGCGCCTGCCATACCCCCTCCCCCACCCACCCACACACACCATCCGGGCCCACGGTGGGACCCAGATGTCATGCGCTGTACGGGCGAGCAACTAGCCCCCACCTCTTCCCAAGAGGCAAAACCT'
Using device: cpu
Traceback (most recent call last):
  File "/data/Software/PDLLMs/model_inference.py", line 49, in <module>
    main()
  File "/data/Software/PDLLMs/model_inference.py", line 21, in main
    model = ModelInference(
            ^^^^^^^^^^^^^^^
  File "/data/Software/PDLLMs/pdllib/inference.py", line 23, in __init__
    self._load_model_and_tokenizer()
  File "/data/Software/PDLLMs/pdllib/inference.py", line 79, in _load_model_and_tokenizer
    self.model = AutoModelForSequenceClassification.from_pretrained(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Software/miniconda32024/envs/llms/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Software/miniconda32024/envs/llms/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3789, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by ljq12697** [comment]
This error is possibly caused by the incomplete download of the model file. 
Please check if `git-lfs` has been installed, then try to re-download the model and run the script again.

**Comment by wangzwYYDS** [comment]
thank you so much ...  my problem is solved.  
i re-install git lfs , ,then re-download the model  , example can run.
