### ISSUE TITLE
"AttributeError: 'float' object has no attribute 'size' during evaluation in compute_metrics"

### ISSUE THREAD

**Issue by sixgod696** [zhangtaolab/Plant_DNA_LLMs#9]
100%|█████████▉| 2077/2080 [00:44<00:00, 46.37it/s][ATraceback (most recent call last):
  File "/data1/users/miaolin/lulei/llms/Plant_DNA_LLMs/model_finetune.py", line 629, in <module>
    train()
  File "/data1/users/miaolin/lulei/llms/Plant_DNA_LLMs/model_finetune.py", line 614, in train
    trainer.train()
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/transformers/trainer.py", line 2035, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/transformers/trainer.py", line 2321, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/transformers/trainer.py", line 3053, in evaluate
    output = eval_loop(
             ^^^^^^^^^^
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/transformers/trainer.py", line 3353, in evaluation_loop
    metrics = self.compute_metrics(EvalPrediction(predictions=all_preds, label_ids=all_labels))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/users/miaolin/lulei/llms/Plant_DNA_LLMs/model_finetune.py", line 400, in compute_metrics
    return clf_metrics.compute(predictions=predictions, references=labels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/evaluate/module.py", line 979, in compute
    results.append(evaluation_module.compute(**batch))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data1/users/tangping/software/conda/envs/llms/lib/python3.11/site-packages/evaluate/module.py", line 467, in compute
    output = self._compute(**inputs, **compute_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tangping/.cache/huggingface/modules/evaluate_modules/metrics/recall/e40e6e98d18ff3f210f4d0b26fa721bfaa80704b1fdf890fa551cfabf94fc185/recall.py", line 135, in _compute
    return {"recall": float(score) if score.size == 1 else score}
                                      ^^^^^^^^^^
AttributeError: 'float' object has no attribute 'size'  

Hello, I repeatedly encounter the above error when attempting reasoning. Could you please explain the cause and how to resolve it? I look forward to your response. Additionally, I left an issue on Gitee a few days ago but have not received any reply. You can also respond there if it's more convenient.

**Comment by ljq12697** [comment]
Could you please provide your python packages' version in the requirements.txt?  This may be caused by a bug of evaluate or scikit-learn package.

**Comment by sixgod696** [comment]
> Could you please provide your python packages' version in the requirements.txt? This may be caused by a bug of evaluate or scikit-learn package.

requirements.txt：
accelerate
datasets
evaluate
numpy<2.0
peft
scipy
scikit-learn
torch
tqdm
transformers<4.43
modelscope<=1.19.1 

pip-list：
Package                  Version
------------------------ -----------
accelerate               1.2.0
aiohappyeyeballs         2.4.4
aiohttp                  3.11.10
aiosignal                1.3.1
attrs                    24.2.0
certifi                  2024.8.30
charset-normalizer       3.4.0
datasets                 3.2.0
dill                     0.3.8
evaluate                 0.4.3
filelock                 3.16.1
frozenlist               1.5.0
fsspec                   2024.9.0
git-lfs                  1.6
huggingface-hub          0.26.5
idna                     3.10
Jinja2                   3.1.4
joblib                   1.4.2
MarkupSafe               3.0.2
modelscope               1.19.1
mpmath                   1.3.0
multidict                6.1.0
multiprocess             0.70.16
networkx                 3.4.2
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.85
nvidia-nvtx-cu12         12.1.105
packaging                24.2
pandas                   2.2.3
peft                     0.4.0
pip                      24.2
propcache                0.2.1
psutil                   6.1.0
pyarrow                  18.1.0
python-dateutil          2.9.0.post0
pytz                     2024.2
PyYAML                   6.0.2
regex                    2024.11.6
requests                 2.32.3
safetensors              0.4.5
scikit-learn             1.6.0
scipy                    1.14.1
setuptools               75.1.0
six                      1.17.0
sympy                    1.13.3
threadpoolctl            3.5.0
tokenizers               0.13.3
torch                    2.3.1
tqdm                     4.67.1
transformers             4.30.2
triton                   2.3.1
typing_extensions        4.12.2
tzdata                   2024.2
urllib3                  2.2.3
wheel                    0.44.0
xxhash                   3.5.0
yarl                     1.18.3

**Comment by ljq12697** [comment]
OK, I have saw your package versions. We have updated the requirements several days ago, perhaps you cloned the repository early. 
You can try to downgrade the scikit-learn to 1.5.0, as is shown in the current requirements.txt.
By the way, I checked your issue on Gitee, for testing the code fastly, you can use a small training dataset by subsampling the original dataset.

**Comment by sixgod696** [comment]
Thank you for your detailed response, I will give it a try.

**Comment by sixgod696** [comment]
> OK, I have saw your package versions. We have updated the requirements several days ago, perhaps you cloned the repository early. You can try to downgrade the scikit-learn to 1.5.0, as is shown in the current requirements.txt. By the way, I checked your issue on Gitee, for testing the code fastly, you can use a small training dataset by subsampling the original dataset.
Thank you for your detailed response, I will give it a try.
